const RFQ_CONSTANTS = {
    PENDING_QUOTATION: "PENDING_QUOTATION",
    QUOTATION_IN_PROGRESS: "QUOTATION_IN_PROGRESS",
    PENDING_ISSUE: "PENDING_ISSUE",
    CLOSED: "CLOSED",
    CLOSED_FE: "RFQ CLOSED",
    CLOSE: "CLOSE",
    SUBMIT: "SUBMIT",
    SAVE_AS_DRAFT: "SAVE_AS_DRAFT",
    EDIT: "EDIT",
    EDIT_QUOTATION: "EDIT_QUOTATION",
    SUBMIT_QUOTATION: "SUBMIT_QUOTATION",
    CANCEL: "CANCEL",
    CANCELLED: "CANCELLED",
    RECALLED: "RECALLED",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    SHORTLISTED: "SHORTLISTED",
    SENT_BACK: "SENT_BACK",
    APPROVED: "APPROVED",
    SHORTLIST: "SHORTLIST",
    RECALL: "RECALL",
    SEND_BACK: "SEND_BACK",
    COMPLETED: "COMPLETED",
    CONVERTED_TO_PO: "CONVERTED_TO_PO",
    CONVERTED_TO_CONTRACT: "CONVERTED_TO_CONTRACT"
};

Object.freeze(RFQ_CONSTANTS);
export default RFQ_CONSTANTS;
