const INVOICE_CONSTANTS = {
    DO: "DO_INVOICE",
    PO: "PO_INVOICE",
    OPC: "OPC_INVOICE",
    NON_OPC: "NON_OPC_INVOICE",
    NON_PO: "NON_PO_INVOICE",
    PROJECT_INVOICE_CREATED: "PROJECT_INVOICE_CREATED",
    NON_PO_INVOICE_CREATED: "NON_PO_INVOICE_CREATED",
    ISSUE_PENDING_APPROVAL_INVOICE: "ISSUE_PENDING_APPROVAL_INVOICE",
    INVOICE_APPROVED: "INVOICE_APPROVED",
    REJECT_PENDING_APPROVAL_INVOICE: "REJECT_PENDING_APPROVAL_INVOICE",
    APPROVED_TWO_WAY: "APPROVED_TWO_WAY",
    APPROVED_THREE_WAY: "APPROVED_THREE_WAY",
    DO_INVOICE_CREATED: "DO_INVOICE_CREATED",

    CONVERT_BY_ARCHITECT: "CONVERT_BY_ARCHITECT",
    PENDING_INVOICE_APPROVAL: "PENDING_INVOICE_APPROVAL",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    APPROVED_INVOICE: "APPROVED_INVOICE",
    REJECTED: "REJECTED",
    INVOICE_REJECTED: "INVOICE_REJECTED",
    INVOICE_REISSUED: "INVOICE_REISSUED"

};

export const STATUS_DEVELOPER_INVOICE = [
    INVOICE_CONSTANTS.CONVERT_BY_ARCHITECT,
    INVOICE_CONSTANTS.PENDING_INVOICE_APPROVAL,
    INVOICE_CONSTANTS.PENDING_APPROVAL,
    INVOICE_CONSTANTS.APPROVED_INVOICE,
    INVOICE_CONSTANTS.REJECTED
];

export const INVOICE_TYPE = {
    DVPC_INVOICE_PROJECT: "DVPC_INVOICE_PROJECT",
    DVPC_INVOICE_NON_PROJECT: "DVPC_INVOICE_NON_PROJECT"
};

export const DVPC_INVOICE_TYPE = {
    DVPC_INVOICE_PROJECT: {
        key: "DVPC_INVOICE_PROJECT",
        text: "DVPC invoice project"
    },
    DVPC_INVOICE_NON_PROJECT: {
        key: "DVPC_INVOICE_NON_PROJECT",
        text: "DVPC invoice non-project"
    }
};
export const categoryInvoice = {
    all: "All",
    purchases: "Purchases",
    subconWorkRequests: "Subcon Work Requests",
    developerWorkRequests: "Developer Work Requests"
};
Object.freeze(INVOICE_CONSTANTS);
export default INVOICE_CONSTANTS;
