const PO_STATUS = {
    PENDING_ISSUE: "PENDING_ISSUE",
    ISSUED: "ISSUED",
    ACKNOWLEDGED: "ACKNOWLEDGED",
    PARTIALLY_DELIVERED: "PARTIALLY_DELIVERED",
    CLOSED: "CLOSED",
    DELIVERED: "DELIVERED",
    PENDING_REVIEW: "PENDING_REVIEW",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    RECALLED: "RECALLED",
    SENT_BACK: "SENT_BACK",
    CANCELLED: "CANCELLED",
    REJECTED: "REJECTED",
    VIEWED: "VIEWED",
    NOT_VIEWED: "NOT_VIEWED"
};
const PO_FE_STATUS = {
    PENDING_ISSUE: "PENDING_ISSUE",
    ISSUED: "ISSUED",
    ACKNOWLEDGED: "ACKNOWLEDGED",
    PARTIALLY_DELIVERED: "PARTIALLY_DELIVERED",
    CLOSED: "CLOSED",
    DELIVERED: "DELIVERED",
    PENDING_REVIEW: "PENDING_REVIEW",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    RECALLED: "RECALLED",
    SENT_BACK: "SENT_BACK",
    CANCELLED: "CANCELLED",
    REJECTED: "REJECTED",
    VIEWED: "VIEWED",
    NOT_VIEWED: "NOT_VIEWED"
};

Object.freeze(PO_STATUS);
Object.freeze(PO_FE_STATUS);

export {
    PO_STATUS,
    PO_FE_STATUS
};
