const GR_CONSTANTS = {
    PENDING_RECEIPT: "PENDING_RECEIPT",
    COMPLETED: "COMPLETED",
    REJECTED: "REJECTED",
    PENDING_APPROVAL: "PENDING_APPROVAL",
    APPROVED: "APPROVED",
    SAVED_AS_DRAFT: "SAVED_AS_DRAFT",
    SAVE_AS_DRAFT: "SAVE_AS_DRAFT",
    PENDING_SUBMISSION: "PENDING_SUBMISSION",
    DO: "DO",
    PO: "PO",
    NON_PO: "NON_PO",
    SUBMIT: "submit"
};

Object.freeze(GR_CONSTANTS);
export default GR_CONSTANTS;
